package lexer

type Operator = string

var (
	Keywords = map[string]TokenKind{
		"let":    TokenLet,
		"const":  TokenConst,
		"self":   TokenSelf,
		"switch": TokenSwitch,
		"case":   TokenCase,
		"if":     TokenIf,
		"do":     TokenDo,
		"else":   TokenElse,
		"fn":     TokenFn,
		"for":    TokenFor,
		"in":     TokenIn,
		"import": TokenImport,
		"return": TokenReturn,
		"next":   TokenNext,
		"break":  TokenBreak,
		"cast":   TokenCast,
		"type":   TokenType,
		"test":   TokenTest,
		"true":   TokenBool,
		"false":  TokenBool,
		"nul":    TokenNul,
	}

	TypeKeywords = map[string]TokenKind{
		"string": TokenString,
		"char":   TokenChar,
		"bool":   TokenBool,
		"sint":   TokenSInt,
		"s8":     TokenSInt8,
		"s16":    TokenSInt16,
		"s32":    TokenSInt32,
		"s64":    TokenSInt64,
		"uint":   TokenUInt,
		"u8":     TokenUInt8,
		"u16":    TokenUInt16,
		"u32":    TokenUInt32,
		"u64":    TokenUInt64,
		"f32":    TokenFloat32,
		"f64":    TokenFloat64,
		"any":    TokenAny,
		"map":    TokenMap,
		"struct": TokenStruct,
		"enum":   TokenEnum,
		"union":  TokenUnion,
	}

	Directives = map[string]TokenKind{
		"#distinct":    TokenDistinct,
		"#inline":      TokenInline,
		"#no_inline":   TokenNoInline,
		"#must_use":    TokenMustUse,
		"#fallthrough": TokenFallthrough,
		"#partial":     TokenPartial,
		"#force":       TokenForce,
		"#bake":        TokenBake,
		"#deprecated":  TokenDeprecated,
		"#scope":       TokenScope,
		"#no_init":     TokenNoInit,
		"#line":        TokenLine,
		"#file":        TokenFile,
		"#dir":         TokenDir,
		"#init":        TokenInit,
		"#fini":        TokenFini,
	}

	AssignBinOps = [...]TokenKind{
		TokenAssignSlash,
		TokenAssignMultiply,
		TokenAssignModule,
		TokenAssignMinus,
		TokenAssignPlus,
		TokenAssignOr,
		TokenAssignBitOr,
		TokenAssignAnd,
		TokenAssignBitAnd,
		TokenAssignBitLeftShift,
		TokenAssignBitRightShift,
		TokenAssignBitXor,
	}

	BinOperators = map[TokenKind]Operator{
		TokenEquals:              "==",
		TokenGreater:             ">",
		TokenGreaterOrEqual:      ">=",
		TokenLess:                "<",
		TokenLessOrEqual:         "<=",
		TokenNotEquals:           "!=",
		TokenMultiply:            "*",
		TokenSlash:               "/",
		TokenModule:              "%",
		TokenPlus:                "+",
		TokenMinus:               "-",
		TokenAssignMinus:         "-=",
		TokenAssignMinusOne:      "--",
		TokenAssignPlus:          "+=",
		TokenAssignPlusOne:       "++",
		TokenAssignModule:        "%=",
		TokenAssignMultiply:      "*=",
		TokenAssignSlash:         "/=",
		TokenAnd:                 "&&",
		TokenOr:                  "||",
		TokenAssignAnd:           "&&=",
		TokenAssignOr:            "||=",
		TokenBitAnd:              "&",
		TokenBitOr:               "|",
		TokenBitXOR:              "^",
		TokenBitRightShift:       ">>",
		TokenBitLeftShift:        "<<",
		TokenAssignBitAnd:        "&=",
		TokenAssignBitOr:         "|=",
		TokenAssignBitXor:        "^=",
		TokenAssignBitRightShift: ">>=",
		TokenAssignBitLeftShift:  "<<=",
	}

	UnaryOperators = map[TokenKind]Operator{
		TokenExclamation: "!",
		TokenMinus:       "-",
		TokenBitNot:      "~",
		TokenBitAnd:      "&",
		TokenMultiply:    "*",
	}
)
